MultiLevel/MultiLevel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MultiLevelApp.urls')),

]

MultiLevel/MultiLevelApp/urls.py
from django.urls import path
from .views import register, login, bet_view, logout
from .views import deal, inputcoin, outputcoin, editpassword, viewcoin
from .views import historybet, historydeal, historyinput, historyoutput, historyreceive
from .views import listchild, listf, onlyadmin, resetweek
app_name='app1'
urlpatterns = [
    path('register/', register.as_view(), name='register'),
    path('', login.as_view(), name='login'),
    path('bet_view/', bet_view, name='bet_view'),
    path('logout/', logout, name='logout'),
    path('deal/', deal, name='deal'),
    path('inputcoin/', inputcoin, name='inputcoin'),
    path('outputcoin/', outputcoin, name='outputcoin'),
    path('editpassword/', editpassword, name='editpassword'),
    path('viewcoin/', viewcoin, name='viewcoin'),
    path('historybet/', historybet, name='historybet'),
    path('historydeal/', historydeal, name='historydeal'),
    path('historyinput/', historyinput, name='historyinput'),
    path('historyoutput/', historyoutput, name='historyoutput'),
    path('historyreceive/', historyreceive, name='historyreceive'),
    path('home/', listchild, name='home'),
    path('listf/<str:pk>/', listf, name='listf'),
    path('onlyadmin/', onlyadmin, name='onlyadmin'),
    path('resetweek/', resetweek, name='resetweek'),

]

MultiLevel/templates/dangnhap/dangnhap.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<!-- login23:11-->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <link rel="shortcut icon" type="image/x-icon" href="assets/img/favicon.ico">
    <title>Đăng nhập</title>
    <link rel="stylesheet" type="text/css" href="{% static 'homepage/assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'homepage/assets/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'homepage/assets/css/style.css' %}">
    <!--[if lt IE 9]>
		<script src="{% static 'homepage/assets/js/html5shiv.min.js' %}"></script>
		<script src="{% static 'homepage/assets/js/respond.min.js' %}"></script>
	<![endif]-->
</head>

<body>
                {% if messages %}
                        {% for message in messages %}
                            <div class="alert {{ message.tags }} m-2" id="msg" role="alert">
                                {{ message }}
                            </div>
                        {% endfor %}
                {% endif %}
    <div class="main-wrapper account-wrapper">
        <div class="account-page">
			<div class="account-center">
				<div class="account-box">
                    <form action="" method="POST" class="form-signin">
                        {% csrf_token %}
						<div class="account-logo">
                            <a href="index-2.html"><img src="assets/img/logo-dark.png" alt=""></a>
                        </div>
                        <div class="form-group">
                            <label>Tên đăng nhập</label>
                            <input type="text" name="username" class="form-control">
                        </div>
                        <div class="form-group">
                            <label>Mật khẩu</label>
                            <input type="password" name="password" class="form-control">
                        </div>
                        <div class="form-group text-center">
                            <button type="submit" class="btn btn-primary account-btn">Đăng nhập</button>
                        </div>
                        <div class="text-center register-link">
                            Bạn chưa có tài khoản <a href="{% url 'app1:register' %}">Đăng ký ngay</a>
                        </div>
                    </form>
                </div>
			</div>
        </div>
    </div>
    <script src="{% static 'homepage/assets/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'homepage/assets/js/popper.min.js' %}"></script>
    <script src="{% static 'homepage/assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'homepage/assets/js/app.js' %}"></script>
    <script>
        setTimeout(function () {
            if ($('#msg').length > 0) {
                $('#msg').remove();
            }
        }, 2000)
        $('#plateViewModal').on('show.bs.modal', function (e) {
            var src = $(e.relatedTarget).attr('image-source');
            $("#plateImg").attr("src", src);
        });
    </script>
</body>


<!-- login23:12-->
</html>