MultiLevel/MultiLevel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MultiLevelApp.urls')),

]

MultiLevel/MultiLevelApp/urls.py
from django.urls import path
from .views import register, login, bet_view, logout
from .views import deal, inputcoin, outputcoin, editpassword, viewcoin
from .views import historybet, historydeal, historyinput, historyoutput, historyreceive
from .views import listchild, listf, onlyadmin, resetweek
app_name='app1'
urlpatterns = [
    path('register/', register.as_view(), name='register'),
    path('', login.as_view(), name='login'),
    path('bet_view/', bet_view, name='bet_view'),
    path('logout/', logout, name='logout'),
    path('deal/', deal, name='deal'),
    path('inputcoin/', inputcoin, name='inputcoin'),
    path('outputcoin/', outputcoin, name='outputcoin'),
    path('editpassword/', editpassword, name='editpassword'),
    path('viewcoin/', viewcoin, name='viewcoin'),
    path('historybet/', historybet, name='historybet'),
    path('historydeal/', historydeal, name='historydeal'),
    path('historyinput/', historyinput, name='historyinput'),
    path('historyoutput/', historyoutput, name='historyoutput'),
    path('historyreceive/', historyreceive, name='historyreceive'),
    path('home/', listchild, name='home'),
    path('listf/<str:pk>/', listf, name='listf'),
    path('onlyadmin/', onlyadmin, name='onlyadmin'),
    path('resetweek/', resetweek, name='resetweek'),

]

MultiLevel/templates/deal.html
{% extends 'index/index.html' %}
    {% block content %}
<div class="col-md-6">
    <div class="card">
        <div class="card-header">
            <strong>Chuyển tiền</strong>
        </div>
        <div class="card-body">
            <form action="" method="post">
                {% csrf_token %}
                <div class="form-group row">
                    <label for="inputPassword3" class="col-sm-3 col-form-label">Số tiền</label>
                    <div class="col-sm-9">
                        <input type="number" class="form-control" id="inputPassword3" name="prime" >
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputPassword3" class="col-sm-3 col-form-label">Người nhận</label>
                    <div class="col-sm-9">
                        <input type="number" class="form-control" id="" name="unto" >
                    </div>
                </div>
                <button type="submit" class="btn btn-primary mt-1">Đồng ý</button>
            </form>
        </div>
    </div>
</div>
    {% endblock %}

MultiLevel/templates/editpassword.html
{% extends 'index/index.html' %}
    {% block content %}
<div class="col-md-6">
    <div class="card">
        <div class="card-header">
            <strong>Đổi mật khẩu</strong>
        </div>
        <div class="card-body">
            <form action="" method="post">
                {% csrf_token %}
                <div class="form-group row">
                    <label for="inputPassword3" class="col-sm-3 col-form-label">Mật khẩu mới</label>
                    <div class="col-sm-9">
                        <input type="password" class="form-control" id="inputPassword3" name="password1" >
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputPassword3" class="col-sm-3 col-form-label">Nhập lại mật khẩu</label>
                    <div class="col-sm-9">
                        <input type="password" class="form-control" id="inputPassword" name="password2" >
                    </div>
                </div>
                <button type="submit" class="btn btn-primary mt-1">Đồng ý</button>
            </form>
        </div>
    </div>
</div>
    {% endblock %}

MultiLevel/templates/inputcoin.html
{% extends 'index/index.html' %}
    {% block content %}
<div class="col-md-6">
    <div class="card">
        <div class="card-header">
            <strong>Nạp tiền</strong>
        </div>
        <div class="card-body">
            <form action="" method="post">
                {% csrf_token %}
                <div class="form-group row">
                    <label for="inputPassword3" class="col-sm-3 col-form-label">Số tiền</label>
                    <div class="col-sm-9">
                        <input type="number" class="form-control" id="inputPassword3" name="prime" >
                    </div>
                </div>
                <button type="submit" class="btn btn-primary mt-1">Đồng ý</button>
            </form>
        </div>
    </div>
</div>
    {% endblock %}

MultiLevel/templates/onlyadmin.html
{% extends 'index/index.html' %}
    {% block content %}
    <div class="col-md-6">
                <li class="nav-item dropdown has-arrow">
                        <a data-toggle="dropdown">
                            <strong>Tổng dao dịch trong tuần:{{total}}</strong>
                        </a>
                </li>
                <li class="nav-item dropdown has-arrow">
                        <a data-toggle="dropdown">
                            <strong>Tổng bonus trong tuần:{{bonus}}</strong>
                        </a>
                </li>
                <form action="">
                    {% csrf_token %}
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Số User LV5:</label>
                        <div class="col-sm-9">
                            <h5>{{lv5}}</h5>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label  class="col-sm-3 col-form-label">Số User LV4:</label>
                        <div class="col-sm-9">
                            <h5>{{lv4}}</h5>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label  class="col-sm-3 col-form-label">Số User LV3:</label>
                        <div class="col-sm-9">
                            <h5>{{lv3}}</h5>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label  class="col-sm-3 col-form-label">Số User LV2:</label>
                        <div class="col-sm-9">
                            <h5>{{lv2}}</h5>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Số User LV1:</label>
                        <div class="col-sm-9">
                            <h5>{{lv1}}</h5>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Số User LV0:</label>
                        <div class="col-sm-9">
                            <h5>{{lv0}}</h5>
                        </div>
                    </div>
                </form>
    </div>

            <a href="{% url 'app1:resetweek'%}">
                <div class="p-5">.
                    <button  style="width:7cm ;">Reset</button>
                </div>
            </a>
    {% endblock %}

MultiLevel/templates/outputcoin.html
{% extends 'index/index.html' %}
    {% block content %}
<div class="col-md-6">
    <div class="card">
        <div class="card-header">
            <strong>Rút tiền</strong>
        </div>
        <div class="card-body">
            <form action="" method="post">
                {% csrf_token %}
                <div class="form-group row">
                    <label for="inputPassword3" class="col-sm-3 col-form-label">Số tiền</label>
                    <div class="col-sm-9">
                        <input type="number" class="form-control" id="inputPassword3" name="prime" >
                    </div>
                </div>
                <button type="submit" class="btn btn-primary mt-1">Đồng ý</button>
            </form>
        </div>
    </div>
</div>
    {% endblock %}

MultiLevel/templates/resetweek.html
{% extends 'index/index.html' %}
    {% block content %}
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <strong>Reset Lại Hệ Thống</strong>
                </div>
                <div class="card-body">
                    <form action="" method="POST">
                        {% csrf_token %}
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Bạn có chắc muốn Reset lại không ?</label>
                        </div>
                        <button type="submit" data-href-template="" name="" value="" class="btn btn-primary mt-1">
                           <a href="google.com" >Đồng ý</a>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    {% endblock %}

MultiLevel/templates/viewcoin.html
{% extends 'index/index.html' %}
    {% block content %}
<div class="col-md-6">
    <div class="card">
        <div class="card-header">
            <strong>Thông Tin Ví Của Bạn</strong>
        </div>
        <div class="card-body">
            <form>
                {% csrf_token %}
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Mã code: </label>
                    <div class="col-sm-9">
                        <h7><b>{{form.code}}</b></h7>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Cấp độ: </label>
                    <div class="col-sm-9">
                        <h7><b>{{form.level}}</b></h7>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Số dư ví: </label>
                    <div class="col-sm-9">
                        <h7><b>{{form.coin}}</b></h7>
                    </div>
                </div>
                <a href="{% url 'app1:inputcoin' %}">
                    <h3>Nạp tiền</h3>
                </a>
            </form>
        </div>
    </div>
</div>
    {% endblock %}

MultiLevel/templates/viewf.html
{% extends 'index/index.html' %}
{% block content %}
<div class="d-flex flex" id="content-body">
    <div class="d-flex flex-column flex card">
        <div class="padding">
            <div class="row ">
                <div class="p-4">
                    <h4 style="font-weight: 700;">Danh sách F</h4>
                </div>
                <div class="p-4">
                    <h4 style="font-weight: 700;">Tổng giao dịch hệ thống:  <b>{{total}}</b></h4>
                </div>
                <div class="p-4">
                    <h4 style="font-weight: 700;">Tiền hoa hồng của bạn:  <b>{{bonus}}</b> </h4>
                </div>
                <table id="table" class="table" data-mobile-responsive="true"
                    style="text-align: center;margin-top: 9px;">
                    <thead>
                        <tr>
                            <th data-sortable="true" data-field="stt" style="width: 3cm;">Username</th>
                            <th data-sortable="true" data-field="stt" style="width: 3cm;">Mã code</th>
                            <th data-sortable="true" data-field="bsx" style="width: 5cm;">Level</th>
                            <th data-sortable="true" data-field="date" style="width: 6cm;">Tổng cược tuần</th>
                            <th data-sortable="true" data-field="task" style="width: 2cm;">Tác vụ</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in form %}
                        <tr class=" " data-id="5">
                            <td style="min-width:20px;">
                                <small class="text-muted">{{ i.username }}</small>
                            </td>
                            <td style="min-width:20px;">
                                <small class="text-muted">{{ i.code }}</small>
                            </td>
                            <td>{{i.level}}</td>
                            <td>{{i.total_deal}}</td>
                            <td class="text-right">
                                <div class="dropdown dropdown-action">
                                    <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown"
                                        aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a class="dropdown-item" href="{% url 'app1:listf' i.code %}"><i
                                                class="fa fa-pencil m-r-5"></i>Danh sách F</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}